name: "Run Makefile Target"
description: "Triggers Makefile target in kubewarden-end-to-end-tests repository"

inputs:
  make:
    description: "The Makefile target to run"
    required: true
    default: "check"

runs:
  using: "composite"
  steps:
    - name: Checkout kubewarden-end-to-end-tests
      uses: actions/checkout@v5
      with:
        repository: ${{ github.repository_owner }}/kubewarden-end-to-end-tests
        ref: main
        path: action-make

    - name: Validate input
      run: |
        # Only allow safe characters: letters, numbers, hyphens, underscores, spaces, dots, equals
        if [[ ! "${{ inputs.make }}" =~ ^[a-zA-Z0-9_\ -.=]+$ ]]; then
          echo "Error: Invalid characters in make targets"
          exit 1
        fi
      shell: bash

    - name: Execute Makefile target
      run: make ${{ inputs.make }}
      working-directory: action-make
      shell: bash
