apiVersion: policies.kubewarden.io/v1alpha2
kind: PolicyServer
metadata:
  name: e2e-tests
spec:
  image: ghcr.io/kubewarden/policy-server:v0.2.5
  replicas: 1
  serviceAccountName: sa
  env:
  - name: KUBEWARDEN_LOG_LEVEL
    value: info
