#!/bin/bash

# Build Airgap
# This script will build an airgap bundle using hauler
# It will download k3s and kubewarden artifacts and store them in a hauler store
# Finally it will export the hauler store to a tar file
# Usage: build-airgap <K3S_VERSION> <TEST_TYPE>
# Example: build-airgap v1.26.4+k3s1 install|upgrade
# Note: TEST_TYPE is used to determine which hauler manifest to use (install or upgrade)

set -vx

# Error function
function error() {
  echo -e "$@" >&2
  exit 1
}

# Retry helm command in case of sporadic issue
function RunHelmCmdWithRetry() {
  # Wait for a maximum of 1 minute
  for ((i = 0; i < 60; i++)); do
    # If helm command is OK then we simply return (exit the function)
    helm $* && return

    # Wait a little
    sleep 5
  done

  # If we are here then an error happened!
  exit 1
}

# Retry skopeo command in case of sporadic issue
function RunSkopeoCmdWithRetry() {
  CMD=$*

  # Wait for a maximum of 1 minute
  for ((i = 0; i < 60; i++)); do
    # If skopeo command is OK then we simply return (exit the function)
    ERRMSG=$(skopeo ${CMD} 2>&1 >/dev/null) && return

    # If resource access is denied retry with local access
    case ${ERRMSG} in
    *requested\ access\ to\ the\ resource\ is\ denied*)
      CMD=${CMD/docker:\/\//docker-daemon:}
      ;;
    *Storing\ signatures\ for\ docker\ tar\ files\ is\ not\ supported*)
      CMD=${CMD/copy/copy --remove-signatures}
      ;;
    esac

    # Wait a little
    sleep 5
  done

  # If we are here then an error happened!
  exit 1
}

# Variable(s)
DEPLOY_AIRGAP_SCRIPT=$(realpath ../scripts/deploy-airgap)
UPGRADE_AIRGAP_SCRIPT=$(realpath ../scripts/upgrade-airgap)
K3S_VERSION=$1
TEST_TYPE=$2
#RANCHER_IMAGES_FILE="rancher-images.txt"
RANCHER_IMAGES_FILE=$(realpath ../assets/images-list)
#RANCHER_LOAD_SCRIPT="rancher-load-images.sh"
#RANCHER_SAVE_SCRIPT="rancher-save-images.sh"

# Validate required arguments
if [[ -z "${K3S_VERSION}" ]] || [[ -z "${TEST_TYPE}" ]]; then
  error "Usage: build-airgap <K3S_VERSION> <TEST_TYPE>\n  K3S_VERSION: e.g. v1.26.4+k3s1\n  TEST_TYPE:   install|upgrade"
fi

KUBEWARDEN_VERSION=latest
KUBEWARDEN_REPO=https://charts.kubewarden.io
HAULER_BIN=/usr/local/bin/hauler
HAULER_PATH="/home/gh-runner/actions-runner/_work/helm-charts/helm-charts/charts"
HAULER_MANIFEST="${HAULER_PATH}/hauler_manifest.yaml"
HAULER_MANIFEST_PREV="${HAULER_PATH}/hauler_manifest_prev.yaml"
OPT_RANCHER="${HOME}/airgap_rancher"
REPO_SERVER="rancher-manager.test:5000"
#IMAGES_PATH="${HOME}/container-images"

# Create directories
#mkdir -p ${OPT_RANCHER}/{k3s,helm,registry} ${IMAGES_PATH}

# The k3s install.sh is a generic installer: the version it installs is controlled at
# runtime via the INSTALL_K3S_VERSION environment variable. We therefore always use the
# install.sh pinned to v1.35.3+k3s1 regardless of K3S_VERSION, avoiding the need to
# maintain per-version checksums. K3S_VERSION still governs which k3s binary and airgap
# images are downloaded below.
K3S_INSTALL_SCRIPT_COMMIT="be38e8843c3498607d41ce583bdbb0ef1e63bba6"
K3S_INSTALL_SCRIPT_SHA256="8598e002e61d658fed7b7542fc6d2c66d8da6eae69e088830105d2ee1ffb6d91"

# Version for which the default checksums below are valid.
K3S_CHECKSUMS_VERSION="v1.35.3+k3s1"

# K3S_BINARY_SHA256 and K3S_AIRGAP_IMAGES_SHA256 can be overridden via environment variables.
# When using a K3S_VERSION other than K3S_CHECKSUMS_VERSION, you MUST set both:
#   K3S_BINARY_SHA256=<sha256 of k3s binary for that version>
#   K3S_AIRGAP_IMAGES_SHA256=<sha256 of k3s-airgap-images-amd64.tar.zst for that version>
# Checksums can be obtained from the release page:
#   https://github.com/k3s-io/k3s/releases/download/<version>/sha256sum-amd64.txt
if [[ "${K3S_VERSION}" != "${K3S_CHECKSUMS_VERSION}" ]]; then
  [[ -n "${K3S_BINARY_SHA256:-}" ]] || error "K3S_BINARY_SHA256 must be set to a non-empty value when K3S_VERSION (${K3S_VERSION}) differs from the default (${K3S_CHECKSUMS_VERSION})"
  [[ -n "${K3S_AIRGAP_IMAGES_SHA256:-}" ]] || error "K3S_AIRGAP_IMAGES_SHA256 must be set to a non-empty value when K3S_VERSION (${K3S_VERSION}) differs from the default (${K3S_CHECKSUMS_VERSION})"
fi
K3S_BINARY_SHA256="${K3S_BINARY_SHA256:-e8661b03d0004e5792da6c2aae7f05de4c54711ee4228d0cce28e02c404626a6}"
K3S_AIRGAP_IMAGES_SHA256="${K3S_AIRGAP_IMAGES_SHA256:-1f929f52845623ba336de4af9b49285f6e5a4c7bbc20cab006d374fb9b75bf37}"

# Install hauler v1.4.2 via install script
HAULER_INSTALL_SCRIPT_SHA256="8089730ce8384dc0d520c67f539ceaaba1243078b2ceacd0deb44fea23628466"
HAULER_INSTALL_SCRIPT="$(mktemp /tmp/hauler-install.XXXXXX.sh)"
trap 'rm -f "${HAULER_INSTALL_SCRIPT}"' EXIT
curl -sSfL "https://raw.githubusercontent.com/hauler-dev/hauler/v1.4.2/install.sh" -o "${HAULER_INSTALL_SCRIPT}" || error "Failed to download hauler install script"
echo "${HAULER_INSTALL_SCRIPT_SHA256}  ${HAULER_INSTALL_SCRIPT}" | sha256sum -c || error "Hauler install script checksum verification failed"
HAULER_VERSION=1.4.2 HAULER_INSTALL_DIR=$HOME bash "${HAULER_INSTALL_SCRIPT}" || error "Failed to run hauler install script"
sudo mv $HOME/hauler ${HAULER_BIN}

# Install packages
sudo zypper --no-refresh -n in skopeo yq

# Create directory
mkdir -p ${OPT_RANCHER}/k3s
cd ${OPT_RANCHER}

# First we need to move docker directory to ensure that we have enough disk space
#if [[ ! -d ${HOME}/var-lib-docker ]]; then
#  sudo systemctl stop docker
#
#  # Move the directory
#  sudo mv /var/lib/docker ${HOME}/var-lib-docker/
#  sudo ln -s ${HOME}/var-lib-docker /var/lib/docker
#
#  # Allow local insecure registry
#  sudo sed -i 's/^{$/{\n  "insecure-registries": ["rancher-manager.test:5000"],/' /etc/docker/daemon.json
#
#  # Restart docker daemon
#  sudo systemctl start docker
#  if ! sudo systemctl is-active --quiet docker; then
#    error "Docker service is not running!"
#  fi
#fi

# Get Helm Charts
#cd ${OPT_RANCHER}/helm/

# Add repos
RunHelmCmdWithRetry repo add jetstack https://charts.jetstack.io > /dev/null 2>&1
RunHelmCmdWithRetry repo add rancher-latest https://releases.rancher.com/server-charts/latest > /dev/null 2>&1
RunHelmCmdWithRetry repo update > /dev/null 2>&1

# Get CertManager chart
RunHelmCmdWithRetry pull jetstack/cert-manager > /dev/null 2>&1

# Get CertManager version
CERT_MANAGER_VERSION=$(ls cert-manager-*.tgz 2>/dev/null)
CERT_MANAGER_VERSION=${CERT_MANAGER_VERSION#cert-manager-*}
CERT_MANAGER_VERSION=${CERT_MANAGER_VERSION%.*}

# Get Rancher chart
RunHelmCmdWithRetry pull rancher-latest/rancher > /dev/null 2>&1

# Get Rancher version from the downloaded chart
RANCHER_VERSION=$(ls rancher-*.tgz 2>/dev/null)
RANCHER_VERSION=${RANCHER_VERSION#rancher-*}
RANCHER_VERSION=${RANCHER_VERSION%.*}

# Get container images
#cd ${IMAGES_PATH}

# Get Rancher images list
#curl -sOL https://github.com/rancher/rancher/releases/download/v${RANCHER_VERSION}/${RANCHER_IMAGES_FILE}

# Rancher scripts
#for I in ${RANCHER_LOAD_SCRIPT} ${RANCHER_SAVE_SCRIPT}; do
#  curl -sOL https://github.com/rancher/rancher/releases/download/v${RANCHER_VERSION}/${I}
#  chmod +x ${I}
#
#  # Workaround to speed up the save/load process
#  sed -i 's/gzip/pigz --fast/' ${I}
#done

# CertManager images list
#RunHelmCmdWithRetry template ${OPT_RANCHER}/cert-manager-${CERT_MANAGER_VERSION}.tgz \
#  | awk '$1 ~ /image:/ {print $2}' \
#  | sed s/\"//g >> ${RANCHER_IMAGES_FILE}

# Sort and clean container images list
#sort -u ${RANCHER_IMAGES_FILE} -o ${RANCHER_IMAGES_FILE}

# Save container images
#./${RANCHER_SAVE_SCRIPT} --image-list ${RANCHER_IMAGES_FILE}

# Export registry with skopeo
#cd ${OPT_RANCHER}
#RunSkopeoCmdWithRetry copy --additional-tag registry:latest docker://registry:latest docker-archive:registry/registry.tar

# Compress all the things but the container images
#tar -I pzstd -vcf ${OPT_RANCHER%/*}/airgap_rancher.zst $(ls 2>/dev/null)

# Add rancher manager in /etc/hosts
sudo sh -c "echo '192.168.122.102 ${REPO_SERVER%:*}' >> /etc/hosts"

# Download k3s binaries and airgap images for the requested K3S_VERSION
K3S_URL=https://github.com/k3s-io/k3s/releases/download/$K3S_VERSION
curl -sSfL ${K3S_URL}/k3s-airgap-images-amd64.tar.zst -o ${OPT_RANCHER}/k3s/k3s-airgap-images-amd64.tar.zst || error "Failed to download k3s-airgap-images-amd64.tar.zst"
echo "${K3S_AIRGAP_IMAGES_SHA256}  ${OPT_RANCHER}/k3s/k3s-airgap-images-amd64.tar.zst" | sha256sum -c || error "Checksum verification failed for k3s-airgap-images-amd64.tar.zst"
curl -sSfL ${K3S_URL}/k3s -o ${OPT_RANCHER}/k3s/k3s || error "Failed to download k3s"
echo "${K3S_BINARY_SHA256}  ${OPT_RANCHER}/k3s/k3s" | sha256sum -c || error "Checksum verification failed for k3s"

# Download the install.sh pinned to the fixed v1.35.3+k3s1 commit and verify its checksum
curl -sSfL "https://raw.githubusercontent.com/k3s-io/k3s/${K3S_INSTALL_SCRIPT_COMMIT}/install.sh" -o ${OPT_RANCHER}/k3s/install.sh || error "Failed to download k3s install.sh"
echo "${K3S_INSTALL_SCRIPT_SHA256}  ${OPT_RANCHER}/k3s/install.sh" | sha256sum -c || error "Checksum verification failed for ${OPT_RANCHER}/k3s/install.sh"

# Get the airgap deploy script
cp ${DEPLOY_AIRGAP_SCRIPT} ${UPGRADE_AIRGAP_SCRIPT} ${OPT_RANCHER}/k3s

# Add k3s artifacts to hauler
${HAULER_BIN} store add file ${OPT_RANCHER}/k3s

# Pull Kubewarden artifacts using the Hauler manifest
cd ${OPT_RANCHER}
if [[ "$TEST_TYPE" == "upgrade" ]] ; then
  ${HAULER_BIN} store sync --filename ${HAULER_MANIFEST_PREV}
else
  ${HAULER_BIN} store sync --filename ${HAULER_MANIFEST}
fi

# Save Rancher images to hauler store
for images in $(cat ${RANCHER_IMAGES_FILE}); do
  ${HAULER_BIN} store add image ${images}
done

# Skopeo - Registry
# We need this image to build our internal registry
RunSkopeoCmdWithRetry copy --additional-tag registry:latest docker://registry:latest docker-archive:registry.tar
${HAULER_BIN} store add file registry.tar

# Export the hauler store
${HAULER_BIN} store save --platform linux/amd64
