name: End-to-end tests

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: "Kwctl"
        uses: kubewarden/github-actions/kwctl-installer@ff49d7af0447a59fe9a58a82805713e1a25539f2 # v4.6.2
        with:
          KWCTL_VERSION: latest

      - name: Dependencies
        run: |
          sudo npm install -g bats
          wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          helm repo add kubewarden https://charts.kubewarden.io

      - name: Checkout tested code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: "true"

      - name: Checkout Helm Charts
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: kubewarden/helm-charts
          sparse-checkout: charts
          path: helm-charts
          ref: main

      - name: Run Tests
        run: make install tests
        env:
          CHARTS_LOCATION: ./helm-charts/charts
