name: End-to-end tests

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: "Kwctl"
        uses: kubewarden/github-actions/kwctl-installer@0f1672d63bd3572f204917d68390d87f7430069a # v5.0.0
        with:
          KWCTL_VERSION: latest

      - name: Download K3d install script
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: k3d-io/k3d
          sparse-checkout: install.sh
          path: tools
          ref: "201b614ea6798f0ee9e75c63360eef891b36bb19" # v5.8.3
          sparse-checkout-cone-mode: false

      - name: Install dependencies
        run: |
          sudo npm install -g bats
          cat tools/install.sh | bash
          helm repo add kubewarden https://charts.kubewarden.io

      - name: Checkout tested code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: "true"

      - name: Checkout Helm Charts
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: kubewarden/helm-charts
          sparse-checkout: charts
          path: helm-charts
          ref: main

      - name: Run Tests
        run: make install tests
        env:
          CHARTS_LOCATION: ./helm-charts/charts
